---
# tasks file for nginx_test
   - name: Nginx Test -1- Check Nginx is running
     shell: systemctl status nginx
     register: nginx_status
     changed_when: False
     failed_when: "'running' not in nginx_status.stdout"

   - name: Nginx Test -2- Nginx status
     debug:
       msg: "nginx installed and is running {{nginx_status.stdout[2]}}"
