---
# tasks file for java_test
   - name: Check Java is running
     command: java -version
     register: java_status

   - name: Java status
     debug:
       msg: "Java installed and is running {{java_status}}"
