# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "/home/student/Downloads/centos-7.4-x86_64-minimal.box"

  config.vm.define "day2" do |node|
	node.vm.network "private_network", ip: "192.168.56.22"
	node.vm.hostname = "day2"
	node.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
#		vb.name = "day2"
	end
  end

end


