---
# tasks file for tomcat_test
   - name: Tomcat Test -1- Check Tomcat is running
     shell: systemctl status tomcat | grep Active
     register: tomcat_status
     changed_when: False
     failed_when: "'running' not in tomcat_status.stdout"

   - name: Tomcat Test -2- Tomcat_status
     debug:
       msg: "{{tomcat_status}}"

   - name: Tomcat Test -3- 2nd check Tomcat status
     shell: ps -ef | grep tomcat
     register: tomcat_process
     changed_when: False
     failed_when: "'catalina' not in tomcat_process.stdout"

   - name: Tomcat Test -4- Tomcat status
     debug:
       msg: "{{tomcat_process}}"
